set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Add all your plugins here (note older versions of Vundle used Bundle instead of Plugin)


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" 常用命令
" " :PluginList       - 查看已经安装的插件
" " :PluginInstall    - 安装插件
" " :PluginUpdate     - 更新插件
" " :PluginSearch     - 搜索插件，例如 :PluginSearch xml就能搜到xml相关的插件
" " :PluginClean      - 删除插件，把安装插件对应行删除，然后执行这个命令即可



" Enable folding
set foldmethod=indent
set foldlevel=99
" Enable folding with the spacebar
nnoremap <space> za

Plugin 'tmhedberg/SimpylFold'
let g:SimpylFold_docstring_preview= 1

" PYthon PEP8
set tabstop=4
set softtabstop=4
set shiftwidth=4
"set textwidth=79
set expandtab
set autoindent
set fileformat=unix


" The most important plugin:
" python-mode
" the autocompletion initial
Plugin 'klen/python-mode'

let g:pymode_rope_completion = 1
let g:pymode_rope_complete_on_dot = 1
let g:pymode_rope_completion_bind = '<Tab>'

"自动检测不启用virtualenv
let g:pymode_virtualenv = 0
" lint 有问题默认把它关掉
"不启用python语法检查
let g:pymode_lint = 0
"不启用重构
let g:pymode_rope = 1
"不在父目录下查找.ropeproject，能提升响应速度
let g:pymode_rope_lookup_project = 0

"<C-c>g跳转到定义处，同时新建竖直窗口打开
let g:pymode_rope_goto_definition_bind = '<C-c>g'
let g:pymode_rope_goto_definition_cmd = 'vnew'

"check grammer
"Plugin 'scrooloose/syntastic'

let python_highlight_all=1
syntax on  " let the highlight on;
set number " let the number display on the lift one
set showcmd 
set cursorline        "突出显示当前行"
"set cursorcolumn       "突出显示当前列"

set nocompatible
set backspace=indent,eol,start

" 状态栏

Plugin 'Lokaltog/vim-powerline'

" 自动补全右边
Plugin 'jiangmiao/auto-pairs'

" 树形exporer
Plugin 'scrooloose/nerdtree'
"F2开启和关闭树"
map <F2> :NERDTreeToggle<CR>
let NERDTreeChDirMode=1
"显示书签"
let NERDTreeShowBookmarks=1
"设置忽略文件类型"
let NERDTreeIgnore=['\~$', '\.pyc$', '\.swp$']
"窗口大小"
let NERDTreeWinSize=25







