syntax on  " let the highlight on;
set number " let the number display on the lift one
set showcmd 

set autoindent
set cindent

set softtabstop=4
set shiftwidth=4

set nocompatible
set backspace=indent,eol,start
